# -*- coding: utf-8 -*-
"""Copy of Case Study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxotXlZX-4W3qjYtOQXiq-ERwBEX5PqL
"""

# Case Study 1
# Grocery Store Calculator

def main():
    items = []
    total = 0.0

    count = int(input("Enter the number of items: "))

    for i in range(count):
        name = input(f"Enter name of item {i + 1}: ")
        price = float(input(f"Enter price of {name}: "))
        quantity = int(input(f"Enter quantity of {name}: "))
        items.append((name, price, quantity))

    tax_rate = float(input("Enter tax rate (in percentage): "))

    print("\n---- Grocery Bill ----")
    print(f"{'Item':<20}{'Price':<10}{'Quantity':<10}{'Total':<10}")

    for name, price, quantity in items:
        item_total = price * quantity
        total += item_total
        print(f"{name:<20}{price:<10.2f}{quantity:<10}{item_total:<10.2f}")

    tax_amount = (tax_rate / 100) * total
    final_total = total + tax_amount

    print("------------------------------")
    print(f"Subtotal: {total:.2f}")
    print(f"Tax ({tax_rate:.2f}%): {tax_amount:.2f}")
    print(f"Final Total: {final_total:.2f}")

if __name__ == "__main__":
    main()